{
  "branches": [ "master" ],
  "repositoryUrl": "https://github.com/AugustoFKL/sql-helper",
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    [ "@semantic-release/github", {
      "assets": [
        { "path": "target/release/libsql_helper.rlib", "label": "sql-helper" },
      ]
    } ],
  ]
}